version: '3.3'

networks:
  rescado-network:
    driver: bridge

services:
  rescado-store:
    container_name: 'rescado-store'
    image: 'postgis/postgis:14-3.2'
    environment:
      POSTGRES_DB: '${RESCADO_DATASOURCE_NAME:-rescado}'
      POSTGRES_USER: '${RESCADO_DATASOURCE_USERNAME:-rescado_user}'
      POSTGRES_PASSWORD: '${RESCADO_DATASOURCE_PASSWORD:-rescado_password}'
    networks:
      - 'rescado-network'
    ports:
      - '5454:5432' # allow access on host on port 5454 even tho rescado-server will connect on port 5432 over rescado-bridge
    volumes:
      - './db/data:/var/lib/postgresql/data'

  rescado-server:
    container_name: 'rescado-server'
    image: 'rescado/rescado-server:latest'
    environment:
      SPRING_DATASOURCE_URL: 'jdbc:postgresql://${RESCADO_DATASOURCE_HOST:-rescado-store}:5432/${RESCADO_DATASOURCE_NAME:-rescado}'
      SPRING_DATASOURCE_USERNAME: '${RESCADO_DATASOURCE_USERNAME:-rescado_user}'
      SPRING_DATASOURCE_PASSWORD: '${RESCADO_DATASOURCE_PASSWORD:-rescado_password}'
    depends_on:
      - 'rescado-store'
    networks:
      - 'rescado-network'
    ports:
      - '8282:8282'
    volumes:
      - './log:/log'
    restart: on-failure:5
