name: upload image

on:
  push:
    branches:
      - develop # TODO switch back to main when stable

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}

    steps:
      - name: Setup Java 11
        id: setup-java
        uses: actions/setup-java@v2.3.1
        with:
          distribution: 'adopt'
          java-version: '11'
      - name: Checkout codebase
        id: checkout-codebase
        uses: actions/checkout@v2.3.4
      - name: Log in to DockerHub
        id: connect-docker
        uses: docker/login-action@v1.10.0
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build Docker image
        id: build-image
        run: ./gradlew clean build jibDockerBuild
      - name: Push Docker image
        id: push-image
        run: docker push rescado/rescado-server --all-tags
      - name: Send status to Slack
        uses: act10ns/slack@v1.2.2
        with:
          status: ${{ job.status }}
          steps: ${{ toJson(steps) }}
        if: always()
